### ISSUE TITLE
Tech Section

### ISSUE THREAD

**Issue by mdnasirulhaque** [gdgcloudkol/chapter-website#3]
![image](https://github.com/gdgcloudkol/chapter-website/assets/30960574/cfef4b8b-6d78-4545-bfe8-37fae875a020)

carousal to be implemented on an array of items
create imgs based on some reference from ts files and not hard coded
create tiles with dynamic data and not hard coded

**Comment by maaz619** [comment]
Technology part is done.
<img width="1432" alt="Screenshot 2024-03-27 at 19 47 46" src="https://github.com/gdgcloudkol/chapter-website/assets/23162832/0bc78051-2157-45ca-9273-1596f4a37bc9">

**Comment by mdnasirulhaque** [comment]
![image](https://github.com/gdgcloudkol/chapter-website/assets/30960574/ffdabbf4-01e7-4a8a-97c6-3c2e892f777d)


Addressed Changes
